version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: <%= appName %>
    environment:
      - DATABASE_URL=<%= databaseUrl %>
      - FOREST_AUTH_SECRET=<%= forestAuthSecret %>
      - FOREST_ENV_SECRET=<%= forestEnvSecret %>
      <% if (!ssl) {%># <% } %>- SSL_DATABASE=true
      <% if (!encrypt) {%># <% } %>- ENCRYPT_DATABASE=true
      <% if (forestUrl) {%>- FOREST_URL=<%= forestUrl %><% } %>
      <% if (devRenderingId) {%>- DEV_RENDERING_ID=<%= devRenderingId %><% } %>
      <% if (dbSchema) {%>- DATABASE_SCHEMA=<%= dbSchema %><% } %>
      <% if (port) {%>- PORT=<%= port %><% } %>
    ports:
      - "<%= port %>:<%= port %>"
