version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: <%= appName %>
    environment:
      - APPLICATION_HOST=<%= hostname %>
      - APPLICATION_PORT=<%= port %>
      - DATABASE_URL=<%= databaseUrl %><% if (dbSchema) { %>
      - DATABASE_SCHEMA=<%= dbSchema %><% } %>
      - DATABASE_SSL=<%= ssl || 'false' %>
      - DATABASE_ENCRYPT=<%= encrypt || 'false' %>
      - FOREST_AUTH_SECRET=<%= forestAuthSecret %>
      - FOREST_ENV_SECRET=<%= forestEnvSecret %>
    ports:
      - "<%= port %>:<%= port %>"
    volumes:
      - ./:/usr/src/app
