sudo: required

language: node_js

node_js: lts/*

env:
  - NODE_ENV=travis

notifications:
  webhooks: https://files-aopiaslhxw.now.sh

services:
  - docker --privileged

before_install:
  - docker-compose --version
  - docker-compose -f docker-compose-min-version.yml up -d
  - docker-compose -f docker-compose-max-version.yml up -d
  - docker ps -a

install:
  - yarn install

script:
  - npm run lint
  - npm run test:ci
