language: node_js
node_js:
  - lts/*
  - 10

services:
  - docker

before_install:
  - docker-compose up -d

install:
  - yarn install

jobs:
  include:
    - stage: Lint & Tests
      name: Lint commit messages
      script: commitlint-travis
    - script: yarn lint
      name: Lint JavaScript
    - script: sleep 15; yarn test
      name: Tests with Node version 10
      node_js: 10
    - script: sleep 15; yarn test
      name: Tests with Node LTS version
    - stage: Build & Publish
      if: branch = master
      script: skip
      deploy:
        provider: script
        on:
          branch: master
        script: yarn && npx semantic-release
