language: node_js
node_js: lts/*

services:
  - docker

before_install:
  - docker-compose up -d

stages:
  - Lint & Tests
  - Build & Publish
    if: branch = master

jobs:
  include:
    - stage: Lint & Tests
      name: Lint commit messages
      script: commitlint-travis
    - script: yarn lint
      name: Lint JavaScript
    - script: sleep 15; yarn test
      name: Tests (Node 10)
      node_js: 10
    - script: sleep 15; yarn test
      name: Tests (Node LTS)
    - stage: Build & Publish
      if: branch = master
      script: skip
      deploy:
        provider: script
        on:
          branch: master
        script: yarn && npx semantic-release
