language: node_js
node_js:
  - lts/*
  - 10

env:
  - NODE_ENV=travis

services:
  - docker --privileged

before_install:
  - docker-compose --version
  - docker-compose up -d
  - docker ps

install:
  - yarn install

script:
  - commitlint-travis
  - yarn lint
  - sleep 15; yarn test
