sudo: required

language: node_js

node_js: lts/*

env:
  - NODE_ENV=travis

notifications:
  webhooks: https://files-aopiaslhxw.now.sh

services:
  - docker --privileged

before_install:
  - docker-compose --version
  - docker-compose up -d
  - docker ps

install:
  - yarn install

script:
  - npm run lint
  - npm run test
