language: node_js
node_js: lts/*

services:
  - docker

stages:
  - Lint & Tests
  - Build & Publish

jobs:
  include:
    - stage: Lint & Tests
      name: Lint commit messages
      script: commitlint-travis
    - script: yarn lint
      name: Lint JavaScript
    - script: sleep 15; yarn test
      before_install: docker-compose up -d
      name: Tests (Node 10)
      node_js: 10
    - script: sleep 15; yarn test
      before_install: docker-compose up -d
      name: Tests (Node LTS)
    - stage: Build & Publish
      if: branch = master AND type != pull_request
      script: skip
      deploy:
        provider: script
        on:
          branch: master
        script: yarn && npx semantic-release
