sudo: required

language: node_js

node_js: lts/*

env:
  - NODE_ENV=travis

notifications:
  webhooks: https://files-aopiaslhxw.now.sh

install:
  - yarn install

script:
  - npm run lint
  - npm run test
