CREATE TABLE [dbo].users (
  id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  username varchar(25) NOT NULL,
  enabled bit CONSTRAINT defo_users_enabled DEFAULT true,
  last_login timestamp NOT NULL CONSTRAINT defo_users_last_login DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id)
);